version: 1
build:
  services:
    - type: web
      name: Cine Cobos
      env: python
      image: python:3.11
      commands:
        - apt-get update && apt-get install -y --no-install-recommends unixodbc-dev
        - python -m venv .venv
        - source .venv/bin/activate
        - pip install -r requirements.txt
      startCommand: gunicorn app:app
