version: 1
build:
  services:
    - type: web
      name: Cine Cobos  # Reemplaza CON EL NOMBRE EXACTO DE TU SERVICIO WEB EN RENDER
      env: python
      image: python:3.11  # Asegúrate de que la versión de Python coincida con tu entorno local y la configuración de Render
      commands:
        - apt-get update && apt-get install -y --no-install-recommends unixodbc-dev
        - pip install -r requirements.txt
      startCommand: gunicorn "app:crear_app()"  # Asumiendo que tu objeto Flask app se llama 'app' en app.py
